### ISSUE TITLE
项目许可证不明确

### ISSUE THREAD

**Issue by hosiet** [yetist/lunar-date#15]
在更新 Debian 中的 lunar-date 软件包 https://tracker.debian.org/pkg/lunar-date 时发现了以下问题：

* https://github.com/yetist/lunar-date/blob/4435eb40828d63094f053fd370595ff8a4f7e110/COPYING 内容为 `GPL-2.0`
* https://github.com/yetist/lunar-date/blob/56f0e9b85a2d0617e56ff160f8ac23bb2ae86d24/meson.build#L3 指出项目许可证为 `LGPL-2.1+`
* 文件内注释一部分采用 `GPL-2.0+`，另一部分采用 `GPL-3.0+`

看上去 `LGPL-2.1+` 可能是笔误；如果是笔误的话希望能够检查一下并修正，整体项目便可以作为 GPL2+ 和 GPL3+ 混合授权（实质 GPL3+）来看待。谢谢！

**Comment by yetist** [comment]
改成 `license : 'LGPLv2+'` ？

**Comment by hosiet** [comment]
@yetist 只是在这里写 LGPLv2+ 也不太符合现在代码的实际情况；这里应该根据实际情况（以及开发者的意愿）来填写。

所以现在上游作者对项目整体的授权的考虑具体是选用哪个呢？

* 如果是 GPL 第二版或更新，那么应该在这里填 GPLv2+ 即可解决问题
* 如果是 GPL 第三版或更新，那么应该在这里填 GPLv3+ 即可解决问题
* 如果是 LGPL 第二版或更新，那么应该在这里填 LGPLv2+，并且需要替换 COPYING 文件 https://github.com/yetist/lunar-date/blob/master/COPYING 为 LGPLv2 的文本
* 如果是 LGPL 第2.1版或更新，那么应该在这里填 LGPLv2.1+，并且需要替换 COPYING 文件 https://github.com/yetist/lunar-date/blob/master/COPYING 为 LGPLv2.1 的文本


不出意外应该就是上面四个选项四选一了。这里并不是希望上游更改许可证，而是希望项目许可证信息明确、没有互相矛盾并且能够反映上游的意愿。

**Comment by atzlinux** [comment]
该项目的源代码，除了 meson.build#L3 
<https://github.com/yetist/lunar-date/blob/56f0e9b85a2d0617e56ff160f8ac23bb2ae86d24/meson.build#L3> 
指定为 LGPLv2.1+  外，其它文件都是 GPL2 或者 GPL3 的。

把该项目整体的版权，修改为 |LGPL2.1+ ，也是没有问题的。|

|作为一个提供库的软件包来将， 使用 LGPL 协议，比使用 GPL 
协议，能够更广泛的使用。|

|当然，这个项目最终是否使用 |||LGPL2.1+，或者继续使用 GPL 
协议，还是由您来做决定。||

||
||

|开源版权协议，比较头疼哈，：-）
|

在 2021/12/7 上午9:55, Wu Xiaotian 写道:
>
> 改成 |license : 'LGPLv2+'| ？
>
BTW：版权字符串缩写，使用“LGPL-2.1+”就可以了，不需要带中间的字母 v。

如果你需要将整个项目修改为 LGPL-2.1+， 把项目的 COPYING 文件，变更为 
LGPL-2.1 即可。

目前还有一个最新的 LGPL3 版权协议，也可以考虑。

**Comment by yetist** [comment]
做为一个库，使用 LGPL 比较合适的。COPYING 文件是之前使用 autotools 时自动产生的，源文件头部的是我的 vim 模板新建文件时生成的，结果就导致协议混合了，现在看来有必要整体处理一下 License 问题了。

**Comment by atzlinux** [comment]
项目整体版权协议已经变更为 LGPL-2.1：

https://github.com/yetist/lunar-date/blob/master/NEWS#L6

这个 issue 可以关闭了。
