### ISSUE TITLE
Jieri / Holiday only display Jieqi.

### ISSUE THREAD

**Issue by leavesczp** [yetist/lunar-date#8]
Jieri / Holiday only display Jieqi. 
I see some Solar/Lunar calendar festivals on the code. How do I display them?

**Comment by yetist** [comment]
You can use `lunar_date_strftime` or `lunar_date_get_holiday`.

**Comment by leavesczp** [comment]
> You can use `lunar_date_strftime` or `lunar_date_get_holiday`.

When I set the date to October 1, it does not display the National Day, but instead returns NULL.I tried both C and gjs.

**Comment by yetist** [comment]
It will be ignored in non-Chinese environments, please try `LC_ALL=zh_CN.utf8`.

**Comment by leavesczp** [comment]
> It will be ignored in non-Chinese environments, please try `LC_ALL=zh_CN.utf8`.
> 
> EDIT:
> If you use lunar-calendar, it will be ignored non-Chinese environments.

Thanks.I now know where the problem is. Is this problem caused by Chinese encoding not being mapped to the corresponding character?
Now I can add the `LC_ALL=zh_CN.utf8` environment variable before running the calendar program to make it display the holiday correctly.

**Comment by yetist** [comment]
I don't know if you are using LunarCalendar, I guess you are using it. 

LunarCalendar does not display holiday information in non-Chinese environments. If you want to force display, you can set this environment variable `LUNAR_CALENDAR_IGNORE_NON_CHINESE=1` to display it. 

At this time, in non-Chinese environment, the holiday information will be displayed in pinyin.

Code is here: https://github.com/yetist/lunar-calendar/blob/master/lunar-calendar/lunar-calendar.c#L114

**Comment by yetist** [comment]
Close it.
